// Mocks generated by Mockito 5.4.4 from annotations
// in simple_news_client/test/framework/repository_implementation/source_repository_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:simple_news_client/core/data/data_sources/source_data_source.dart'
    as _i2;
import 'package:simple_news_client/core/domain/source.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SourceDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSourceDataSource extends _i1.Mock implements _i2.SourceDataSource {
  @override
  _i3.Future<List<_i4.Source>> getSources() => (super.noSuchMethod(
        Invocation.method(
          #getSources,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Source>>.value(<_i4.Source>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Source>>.value(<_i4.Source>[]),
      ) as _i3.Future<List<_i4.Source>>);
}
